# CI configuration adapted from [thesis-template-typst](https://github.com/ls1intum/thesis-template-typst)
# Original project licensed under MIT License
name: Build and release thesis

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_release_thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          # lfs: true

      - name: Cache Fonts
        id: cache-fonts
        uses: actions/cache@v4
        with:
          path: ~/.local/share/fonts
          key: fonts-${{ runner.os }}-v2
          restore-keys: |
            fonts-${{ runner.os }}-

      - name: Install Fonts (if not cached)
        if: steps.cache-fonts.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/share/fonts

          # Install New Computer Modern fonts
          wget -O /tmp/newcomputermodern.zip "https://fontesk.com/download/39191"
          unzip /tmp/newcomputermodern.zip -d /tmp/
          cp -r /tmp/*.otf ~/.local/share/fonts/

          # Install Font Awesome
          echo "Installing Font Awesome..."
          FA_VERSION="6.5.1"
          wget -O /tmp/fontawesome.zip "https://use.fontawesome.com/releases/v${FA_VERSION}/fontawesome-free-${FA_VERSION}-desktop.zip"
          unzip /tmp/fontawesome.zip -d /tmp/
          find "/tmp/fontawesome-free-${FA_VERSION}-desktop/" -name "*.otf" -o -name "*.ttf" | xargs -I {} cp {} ~/.local/share/fonts/

          fc-cache -f -v  # Refresh font cache

      - name: Create initial tag
        run: |
          if [ -z "$(git tag -l 'v*')" ]; then
            git tag v0.0.0
          fi

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: 'patch'

      - uses: typst-community/setup-typst@v4
      - run: typst compile cv_de.typ; typst compile cv.typ

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: final
          name: PDF CV
          draft: false
          prerelease: false
          files: |
            cv_de.pdf
            cv.pdf
